image: python:3.7

before_script:
  - pip install .
  - pip install -r requirements_dev.txt

stages:
  - lint
  - test

black:
  stage: lint
  script:
    - black --check src/ tests/

py-3.6:
  stage: test
  image: python:3.6
  script:
    - pytest -vv
  after_script:
    - bash <(curl -s https://codecov.io/bash)

py-3.7:
  stage: test
  image: python:3.7
  script:
    - pytest -vv
  after_script:
    - bash <(curl -s https://codecov.io/bash)

py-3.8:
  stage: test
  image: python:3.8-rc
  script:
    - pytest -vv
  after_script:
    - bash <(curl -s https://codecov.io/bash)
